jenkins:
  systemMessage: "Local CI for ft_transcendence"
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${JENKINS_ADMIN_USER:-admin}"
          password: "${JENKINS_ADMIN_PASS:-admin123}"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

unclassified:
  location:
    url: "http://localhost:8082/"

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-https"
              description: "GitHub HTTPS (username + PAT)"
              username: "${GITHUB_USER:-}"
              password: "${GITHUB_PAT:-}"

# Job DSL через JCasC — создаём multibranch Pipeline
jobs:
  - script: >
      multibranchPipelineJob('ft_transcendence') {
        branchSources {
          branchSource {
            source {
              github {
                id('gh-ft-transcendence')
                repoOwner('olnytim')
                repository('ft_transcendence')
                repositoryUrl("${GITHUB_CLONE_URL:-https://github.com/olnytim/ft_transcendence.git}")
                configuredByUrl(true)
                credentialsId("${GH_CRED_ID:-github-https}")
                traits {
                  gitHubBranchDiscovery { strategyId(3) }      // branches + PRs
                  gitHubPullRequestDiscovery { strategyId(1) } // PRs from forks
                }
              }
            }
          }
        }
        facto
